
SGS_LIB_PATH=../../target/release
SGS_INCLUDE_PATH=../../ffi/include
LDLIBS=-L$(SGS_LIB_PATH) -lsgs
CFLAGS = -g -Wall -O3 -I$(SGS_INCLUDE_PATH)
CC=gcc
PROGRAM=sgs_example
OBJECTS=

$(PROGRAM): $(OBJECTS)